# Generated by Django 4.0.3 on 2023-02-23 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.category'),
        ),
    ]
